global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'my_web_app'
    static_configs:
      - targets: ['0.0.0.0:8000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
